#!/bin/bash
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${BOTMON_DB_USER} WITH ENCRYPTED PASSWORD '${BOTMON_DB_PASSWORD}';
    CREATE DATABASE ${BOTMON_DB_NAME};
    ALTER USER ${BOTMON_DB_USER} CREATEDB;
EOSQL
