# Generated by Django 4.1.6 on 2023-03-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_targetbot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixed_at', models.DateTimeField(null=True)),
                ('sent', models.BooleanField(default=False)),
                ('target_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.targetbot')),
            ],
        ),
    ]
