apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "socks-proxy.fullname" . }}
  labels:
    {{- include "socks-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "socks-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "socks-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sshpass
          args:
            - -p
            - "{{ .Values.password }}"
            - ssh
            - -oServerAliveInterval=100
            - -oStrictHostKeyChecking=no
            - -D
            - "0.0.0.0:{{ .Values.service.port }}"
            - -N
            - "{{ .Values.username }}@{{ .Values.host }}"
          ports:
            - name: socks
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            requests:
              {{- toYaml .Values.resources | nindent 14 }}
            limits:
              {{- toYaml .Values.resources | nindent 14 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
