apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "botmon.fullname" . }}-alert-updater
  labels:
    botmon-service: alert-updater
spec:
  replicas: 1 # Hardcoded to prevent concurrency issues.
  selector:
    matchLabels:
      botmon-service: alert-updater
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        botmon-service: alert-updater
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-alert-updater
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - python
            - -u
            - manage.py
            - alertupdater
            - --period
            - "{{ .Values.healthCheck.periodSeconds }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
            {{- toYaml .Values.resources | nindent 14 }}
            requests:
          {{- toYaml .Values.resources | nindent 14 }}
          env:
            - name: BOTMON_TELEGRAM_AGENT_SESSION_STRING
              value: "{{ .Values.telegramClient.sessionString }}"
            - name: BOTMON_TELEGRAM_AGENT_API_ID
              value: "{{ .Values.telegramClient.apiId }}"
            - name: BOTMON_TELEGRAM_AGENT_API_HASH
              value: "{{ .Values.telegramClient.apiHash }}"
            - name: BOTMON_TELEGRAM_AGENT_HEALTH_CHECK_MESSAGE
              value: "{{ .Values.healthCheck.pingMessage }}"
            - name: BOTMON_TELEGRAM_AGENT_HEALTH_CHECK_TIMEOUT_SECONDS
              value: "{{ .Values.healthCheck.timeoutSeconds }}"
            - name: BOTMON_SECRET_KEY
              value: "{{ .Values.secretKey }}"
            - name: DJANGO_SETTINGS_MODULE
              value: "{{ .Values.djangoSettingsModule }}"
            - name: BOTMON_DB_HOST
              value: "{{ .Values.database.host }}"
            - name: BOTMON_DB_PORT
              value: "{{ .Values.database.port }}"
            - name: BOTMON_DB_NAME
              value: "{{ .Values.database.name }}"
            - name: BOTMON_DB_USER
              value: "{{ .Values.database.user }}"
            - name: BOTMON_DB_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: BOTMON_TELEGRAM_PROXY_URL
              value: {{ .Values.proxyUrl }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
