apiVersion: v1
kind: Service
metadata:
  name: {{ include "botmon.fullname" . }}
  labels:
    {{- include "botmon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: backend
      protocol: TCP
      name: http
  selector:
    {{- include "botmon.selectorLabels" . | nindent 4 }}
